Fix problem with unprocessed Pull Requests in SonarQube
mc1arke/sonarqube-community-branch-plugin pull request #796
Opened 2023-08-28 13:05 UTC by jero-dev

Related to the issue #738, it's true that any type of project should be created with a Pull Request that their target branch is not scanned yet.

But the problem comes when the Pull Request, which its target branch is scanned, is waiting for being processed when there's a heavy project in progress status in the Background tasks section. Because SonarQube didn't add the proper Pull Request data to the project until is processed, we have the same problem as was described in the issue mentioned before, even when we have the target branch scan.

So the changes that are added in this Pull Request are simple:

- We ignore these unprocessed Pull Requests in the listing branches action.
- Add a test that covers this use case.

If there's any doubt, please, use this Pull Request for the discussion.

2023-10-02 11:23 UTC, mpet commented
@mc1arke  will this be in release 1.15.0?

2023-12-29 16:24 UTC, mc1arke requested changes

2023-12-29 20:00 UTC, jero-dev commented on src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/ListActionTest.java
> +    void shouldExExcludePullRequestsWithoutData() {
Right. I will refactor it.

2023-12-29 20:00 UTC, jero-dev commented on src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/ListAction.java
> +        if (pullRequestData == null) return;
Sure. I will add them in the new changes.

2024-01-01 13:43 UTC, mc1arke commented
I'm superceding this with #847 since the Pull Request data fields are not mandatory and I'd rather we didn't end up with data in the database that wasn't visible in the API, as users then don't know if they've got potentially broken data needing cleaned-up. I've also put in a fix for the root cause of the problem reported in the original issue which should mean the data is less likely to get corrupt. Thanks for the contribution though!

2024-01-01 13:43 UTC, closed without merging

2024-01-03 10:53 UTC, jero-dev commented
Awesome! Thank you so much and keep the good work! 😄